version: "3.7"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.php
    restart: unless-stopped
    ports:
      - "10924:80"
    volumes:
      - ./application/public:/var/www/html
      - ./application/config:/var/www/config
      - ./application/lib:/var/www/lib
      - ./application/sockets:/var/www/sockets
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: eireel5Xee5ahKishee9
      MYSQL_DATABASE: muscari
      MYSQL_USER: muscari
      MYSQL_PASSWORD: Zawag3eepheid1eech4H
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
